# Generated by Django 4.2.11 on 2024-04-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_calorie_goal', models.IntegerField()),
                ('notes', models.TextField(max_length=250)),
            ],
        ),
    ]
